name: Install backend dependencies
description: Installs dependencies for python backend

runs:
  using: composite
  steps:
    - name: Set up Python 3.9.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.10"

    - name: Install poetry
      uses: snok/install-poetry@v1.0.0
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        version: 1.1.13

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: backend/.venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      shell: bash
      run: |
        cd backend
        poetry install
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
