# syntax=docker/dockerfile:1

FROM node:16.14.0-buster
ENV NODE_ENV=production

WORKDIR /app

COPY ["frontend/package.json", "frontend/package-lock.json*", "./"]

RUN npm install --production

COPY frontend/ /app

CMD [ "npm", "start" ]