FROM python:3.9.10-buster

WORKDIR /app/ 
COPY scrapper/ /app

ENV PATH="$PATH:/root/.local/bin"

RUN apt-get update && \
    apt-get install -y locales && \
    sed -i -e 's/# pl_PL.UTF-8 UTF-8/pl_PL.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    poetry config virtualenvs.create false && \
    poetry install

CMD [ "poetry", "run" , "flask", "run", "--host=0.0.0.0" ]
