version: "3.9"
services:
  frontend:
    container_name: frontend_calculator
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
  backend:
    container_name: backend_calculator
    environment:
      - DB_URI=mongodb://mongodb_calculator:27017/calculator_data
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "5000:5000"
  mongodb:
    image: mongo:latest
    container_name: mongodb_calculator
    environment:
      - MONGO_INITDB_DATABASE=calculator_data
    volumes:
      - ~/apps/mongo:/data/db
    ports:
       - 172.23.16.1:27017:27017


      
