version: "3.9"
services:
  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "8000:5000"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
