name: innovativeproject-loancalculator

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.10"
    
    - name: Install backend dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create false
        cd backend
        poetry install
    
    - name: Format and lint backend with Black
      run: |
        black .    
    
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.10"
    
    - name: Install backend dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create false
        cd backend
        poetry install
    
    - name: Test backend with pytest
      run: |
        pytest
  
  lint-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node 16.14.0
      uses: actions/setup-node@v2
      with:
        node-version: "16.14.0"
        cache: "npm"
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
  
    - name: Format and lint frontend with eslint and prettier
      run: |
        cd frontend
        npx prettier --write ./src
        npx eslint --fix ./src
  
  
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
  
    - name: Set up Node 16.14.0
      uses: actions/setup-node@v2
      with:
        node-version: "16.14.0"
        cache: "npm"
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Test frontend with npm test
      run: |
        cd frontend
        npm run build --if-present
        npm test
        
  
  build-docker-image:
    runs-on: ubuntu-latest
    needs: [lint-backend, test-backend, lint-frontend, test-frontend]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build docker images
      run: |
        docker-compose -f docker/docker-compose.yaml build
  