name: innovativeproject-loancalculator

on:
  push:
    branches:
      - main
  pull_request:
    branches: '**'
  workflow_dispatch:

jobs:
  lint-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/install-deps
        
    - name: Format and lint backend with Black
      run: |
        cd backend
        poetry run black --check .    
    
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/install-deps

    - name: Test backend with pytest
      run: |
        cd backend
        poetry run pytest

  lint-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: "16.14.0"
        cache: "npm"
        cache-dependency-path: frontend/package-lock.json
  
    - name: Format and lint frontend with eslint and prettier
      run: |
        cd frontend
        npm ci
        npx prettier --write ./src
        npx eslint --fix ./src
  
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: "16.14.0"
        cache: "npm"
        cache-dependency-path: frontend/package-lock.json
    
    - name: Test frontend with npm test
      run: |
        cd frontend
        npm ci
        npm test
        
  build-docker-image:
    runs-on: ubuntu-latest
    needs: [lint-backend, test-backend, lint-frontend, test-frontend]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build docker images
      run: |
        docker-compose -f docker/docker-compose.yaml build
