name: innovativeproject-loancalculator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.10"

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create false
        cd backend
        poetry install

    - name: Format and lint with Black
      run: |
        black .

    # frontend analysis and linting
    # [...]

    - name: Test with pytest
      run: |
        pytest
    
    # frontend testing
    # [...]

    - name: Build docker images
      run: |
        docker-compose -f docker/docker-compose.yaml build